part of 'users_api_client.dart';

/// Temporary implementation for retrofit client.
///
/// This file can be regenerated by `retrofit_generator` when needed.
class _UsersApiClient implements UsersApiClient {
  _UsersApiClient(this._dio, {this.baseUrl});

  final Dio _dio;
  String? baseUrl;

  @override
  Future<List<UserModel>> getUsers() async {
    final String path = _resolvePath(AppUrl.users);
    final Response<List<dynamic>> response = await _dio.get<List<dynamic>>(
      path,
    );

    final List<dynamic> raw = response.data ?? <dynamic>[];
    return raw
        .map((dynamic item) => UserModel.fromJson(_asMap(item)))
        .toList(growable: false);
  }

  String _resolvePath(String path) {
    if (path.startsWith('http://') || path.startsWith('https://')) {
      return path;
    }

    final String customBaseUrl = baseUrl?.trim() ?? '';
    if (customBaseUrl.isEmpty) {
      return path;
    }

    return Uri.parse(customBaseUrl).resolve(path).toString();
  }

  Map<String, dynamic> _asMap(dynamic source) {
    if (source is Map<String, dynamic>) {
      return source;
    }
    if (source is Map) {
      return source.map(
        (dynamic key, dynamic value) => MapEntry('$key', value),
      );
    }
    return <String, dynamic>{};
  }
}
